### ISSUE TITLE
App crashes after a while leaving it open and re-selecting it, using android

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/NativeScript#1614]
_From @Daxito on February 19, 2016 4:4_

So I just open a NS app and then I switch to other apps, then leave my cellphone alone for a while, then when I come back and try to "bring to the front" my App, it crashes with this error:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yyy.yy/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property '_onAttached' of null
File: "/data/data/com.yyy.yy/files/app/tns_modules/ui/frame/frame.js, line: 414, column: 16

StackTrace: 
	Frame: function:'NativeActivity.onCreate', file:'/data/data/com.yyy.yy/files/app/tns_modules/ui/frame/frame.js', line: 414, column: 17

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.access$900(ActivityThread.java:172)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property '_onAttached' of null
File: "/data/data/com.yyy.yy/files/app/tns_modules/ui/frame/frame.js, line: 414, column: 16

StackTrace: 
	Frame: function:'NativeActivity.onCreate', file:'/data/data/com.yyy.yy/files/app/tns_modules/ui/frame/frame.js', line: 414, column: 17

	at com.tns.Platform.callJSMethodNative(Native Method)
	at com.tns.Platform.dispatchCallJSMethodNative(Platform.java:812)
	at com.tns.Platform.callJSMethod(Platform.java:711)
	at com.tns.Platform.callJSMethod(Platform.java:690)
	at com.tns.Platform.callJSMethod(Platform.java:680)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:1574)
	at android.app.Activity.performCreate(Activity.java:6221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
	... 10 more

_Copied from original issue: NativeScript/nativescript-cli#1512_

**Comment by mikeres0** [comment]
+1, any news on this?

**Comment by hshristov** [comment]
@Daxito, @mikeres0 We fixed crash with application suspend resume but by the callstack I see that this might be different problem. Could you please attach sample project and steps to reproduce it?

**Comment by mobilemindtec** [comment]
I saw that the problem happens when clearHistory is true

**Comment by Daxito** [comment]
I have clear history false and it still crashes, I just got it right now.

**Comment by Daxito** [comment]
OK, Here is a demo with the issue, this demo was created just running "tns create sample" and that's it, run this on a real device, android of course, make sure you have many Apps already open, after opening the App, go to different Apps, then come back to this one, it should fail, I had like 17 Apps "Open", or at least were opened at some point. Let me know if you need more info.

[SampleApp.zip](https://github.com/NativeScript/NativeScript/files/156981/SampleApp.zip)

**Comment by orsag** [comment]
Any progress on this issue? We cannot publish to play store with this bug.

**Comment by ErjanGavalji** [comment]
We tested @Daxito's package with the latest build (1.7), which is about to be released and were not able to reproduce the problem. Can you check with it and let us know the state?

Cheers,
Erjan

**Comment by Daxito** [comment]
Will do asap.

**Comment by ErjanGavalji** [comment]
Just to let you know guys, 1.7 is being released now, binaries are out on [npmjs.com](https://npmjs.com) already.

**Comment by Daxito** [comment]
@ErjanGavalji This is still an issue but just with a little different effects, attached is the sample app I used and this is the error I get along with the steps to reproduce it:

**Steps to reproduce**
1. Deploy the sample app to any android real device.
2. Open a bunch of other apps, like 15. 
3. "Bring to the front/select" like 5 or 6 of those others apps before coming back to the SampleApp, the idea it to make SampleApp to be inactivated by the device.
4. Select the SampleApp, now very "inactive", you should see these error in the log, and the app just opens a white window:

`D/TNS.JAVA.JsDebugger(14910): Sending console message to inspector:
{"seq":0,"type":"event","event":"messageAdded","success":true,"body":{"message":{"source":"console-api","type":"log","level":"error","line":0,"column":0,"url":"","groupLevel":7,"repeatCount":1,"text":"The application crashed because of an uncaught exception. You can look at \"stackTrace\" or \"nativeException\" for more detailed information about the exception.\njava.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.SampleApp\/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: \nCalling js method onCreate failed\n\nTypeError: Cannot read property '_onAttached' of null\nFile: \"\/data\/data\/org.nativescript.SampleApp\/files\/app\/tns_modules\/ui\/frame\/frame.js, line: 613, column: 16\n\nStackTrace: \n\tFrame: function:'NativeScriptActivity.onCreate', file:'\/data\/data\/org.nativescript.SampleApp\/files\/app\/tns_modules\/ui\/frame\/frame.js', line: 613, column: 17\n\n\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2661)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)\n\tat android.app.ActivityThread.access$900(ActivityThread.java:172)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:145)\n\tat android.app.ActivityThread.main(ActivityThread.java:5835)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)\nCaused by: com.tns.NativeScriptException: \nCalling js method onCreate failed\n\nTypeError: Cannot read property '_onAttached' of null\nFile: \"\/data\/data\/org.nativescript.SampleApp\/files\/app\/tns_modules\/ui\/frame\/frame.js, line: 613, column: 16\n\nStackTrace: \n\tFrame: function:'NativeScriptActivity.onCreate', file:'\/data\/data\/org.nativescript.SampleApp\/files\/app\/tns_modules\/ui\/frame\/frame.js', line: 613, column: 17\n\n\n\tat com.tns.Platform.callJSMethodNative(Native Method)\n\tat com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)\n\tat com.tns.Platform.callJSMethod(Platform.java:715)\n\tat com.tns.Platform.callJSMethod(Platform.java:694)\n\tat com.tns.Platform.callJSMethod(Platform.java:684)\n\tat com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:14)\n\tat android.app.Activity.performCreate(Activity.java:6221)\n\tat android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)\n\t... 10 more\n"}}}`
 
5. After that error, your app is now dead, it is on the list of "opened" apps but you cannot select it, and even if you tap on the icon itself it just opens a black window (not white anymore), at this point all you can do if "force close" the app.

Please let me know if you need more info, I can provide screenshots if needed.

[SampleApp.zip](https://github.com/NativeScript/NativeScript/files/176206/SampleApp.zip)

**Comment by orsag** [comment]
My app has the same behavior as Daxito's. After resuming it from heavy multitasking white window opens then it turns black, native android back button stops responding and 'force close' is the only option. On the real device with Android 4.4.2 and NS 1.7.

**Comment by enchev** [comment]
Hey @slavchev can you confirm that the sample app in this thread is fixed?

**Comment by slavchev** [comment]
@enchev 

Here are the steps I performed:
* downloaded the app
* replaced `tns-core-modules` with the 1.7.0
* replaced {N} Android runtime with the [latest](https://github.com/NativeScript/android-runtime/commit/a0e4161e0622da1430ac858e2cb96336d96e09f6) from `release` branch 
* `tns run android`
* Tap `NAVIGATE NOW`
* Tap `GOT PAGE2`
* Tap `GOT PAGE3`
* Tap `back` button
* Tap `back` button

So far the app doesn't crash.

**Comment by Daxito** [comment]
@enchev @slavchev 
I hate to be a party pooper but Just FYI, I tested the tns android version 2.0.0-2016-03-18-282 and I still get error (Unable to start activity ... see attached 
[errorLog.txt](https://github.com/NativeScript/NativeScript/files/180631/errorLog.txt)).
The steps to reproduce the issue are the same:
 .1. In your real device, open a bunch of other apps (See attached image, I have like 18 apps open for this test, crashing app is App2 btw)
![screenshot_2016-03-18-23-03-15](https://cloud.githubusercontent.com/assets/16787057/13896563/d54aa756-ed5d-11e5-9a64-57fecb18a403.png)
)

 .2. Create new App using {N} 1.7.0 and the mentioned tns android version and run it.
 .3. Select other apps, like 5 or 10 before selecting your {N} test app again.
 .4. Select your {N} app, the app has to Resume but then it crashes.

Please let me know if you need more info, I am able to duplicate this issue very easy and it is not random.

**Comment by enchev** [comment]
Thank you very much @Daxito! We will verify this before releasing the official version next week.

**Comment by Daxito** [comment]
@slavchev Seems like your change indeed fixes the issue! I just tried it out and no more crashing!
Thank you very much guys!!!
