### ISSUE TITLE
App Crash and white screen on Back Button to quit (android)

### ISSUE THREAD

**Issue by BenElliottBV** [NativeScript/NativeScript#1779]
On exiting the app with the back button, the app appears to close. When reopening, the app is unresponsive and displays a white screen

This appears on Android

- CLI: 1.7.0
- Cross-platform modules: 1.7.0
- Runtime(s): 1.7.0

**Comment by BenElliottBV** [comment]
```
W/System.err( 2108):    at com.tns.Platform.callJSMethod(Platform.java:709)
W/System.err( 2108):    at com.tns.Platform.callJSMethod(Platform.java:694)
W/System.err( 2108):    at com.tns.Platform.callJSMethod(Platform.java:684)
D/TNS.Native( 2108):    at com.tns.Platform.callJSMethod(Platform.java:709)
D/TNS.Native( 2108):    at com.tns.Platform.callJSMethod(Platform.java:694)
D/TNS.Native( 2108):    at com.tns.Platform.callJSMethod(Platform.java:684)
D/TNS.JAVA.JsDebugger( 2108): Sending console message to inspector:{"seq":0,"type":"event","event":"messageAdded","succe
ss":true,"body":{"message":{"source":"console-api","type":"log","level":"error","line":0,"column":0,"url":"","groupLevel
":7,"repeatCount":1,"text":"The application crashed because of an uncaught exception. You can look at \"stackTrace\" or
\"nativeException\" for more detailed information about the exception.\ncom.tns.NativeScriptException: Cannot find objec
t id for instance=com.tns.NativeScriptApplication@21e5ccb0\n\tat com.tns.Platform.callJSMethod(Platform.java:709)\n\tat
com.tns.Platform.callJSMethod(Platform.java:694)\n\tat com.tns.Platform.callJSMethod(Platform.java:684)\n\tat com.tns.Na
tiveScriptApplication.onTrimMemory(NativeScriptApplication.java:30)\n\tat android.app.ActivityThread.handleTrimMemory(Ac
tivityThread.java:4251)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)\n\tat android.os.Hand
ler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:135)\n\tat android.app.ActivityThread.mai
n(ActivityThread.java:5254)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(M
ethod.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)\n\tat com.android.
internal.os.ZygoteInit.main(ZygoteInit.java:698)\n"}}}
```

**Comment by GerjanOnline** [comment]
I'm also experiencing this issue, but for me it also (randomly) fails when using the back button (app crashes with above error message)

**Comment by BenElliottBV** [comment]
![crash](https://cloud.githubusercontent.com/assets/10271559/13819466/68e755aa-eb91-11e5-8ecd-c94a08aac31e.gif)

**Comment by Daxito** [comment]
I also have the same issue, but when switching between apps....at some point when sending the app to the background my console reports the same error message and at that point my app is not responding anymore.

**Comment by slavchev** [comment]
@BenElliottBV 

I fixed an `Application` object initialization bug with this https://github.com/NativeScript/android-runtime/commit/1c6182363cfbc4d55ec09a48739d0451e0baea95. As far I as can see it should fix this issue as well. Can you modify `NativeScriptApplication.java` and `RuntimeHelper.java` files in `<your project>/platforms/android/src/main/java/com/tns` folder to confirm if it works for you or not?

**Comment by sitefinitysteve** [comment]
@slavchev Just overwrite the files and tns run android?

...anyway thats what I did, and I still get the error

**Comment by slavchev** [comment]
Hi @sitefinitysteve 

Thanks for the quick feedback. I will try to reproduce it with your project. Is possible to provide a gist with the error from `logcat`?

**Comment by sitefinitysteve** [comment]
@slavchev Okay, sec
Here's logcat with PREFIX code
https://gist.githubusercontent.com/sitefinitysteve/417ed4919d4a8dec86fe/raw/880179b7459b3867942b00116f52ada19b140360/Android%2520Crash%2520logcat

I can't really give you post change, app doesn't even run
``` js
Successfully deployed on device with identifier '02157df29451570f'.
W/System.err(11606): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err(11606): Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
W/System.err(11606): 	at com.tns.Platform.createJSInstanceNative(Native Method)
W/System.err(11606): 	at com.tns.Platform.createJSInstance(Platform.java:368)
D/TNS.Native(11606): java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
D/TNS.JAVA.JsDebugger(11606): Sending console message to inspector:{"seq":0,"type":"event","event":"messageAdded","success":true,"body":{"message":{"source":"console-api","type":"log","level":"error","line":0,"column":0,"url":"","groupLevel":7,"repeatCount":1,"text":"The application crashed because of an uncaught exception. You can look at \"stackTrace\" or \"nativeException\" for more detailed information about the exception.\njava.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.\n\tat android.app.ActivityThread.handleBindApplication(ActivityThread.java:5935)\n\tat android.app.ActivityThread.access$1700(ActivityThread.java:198)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:145)\n\tat android.app.ActivityThread.main(ActivityThread.java:6837)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:372)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)\nCaused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.\n\tat com.tns.Platform.createJSInstanceNative(Native Method)\n\tat com.tns.Platform.createJSInstance(Platform.java:368)\n\tat com.tns.Platform.initInstance(Platform.java:343)\n\tat com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:112)\n\tat com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:16)\n\tat android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)\n\tat android.app.ActivityThread.handleBindApplication(ActivityThread.java:5932)\n\t... 9 more\n"}}}
```
Logcat doesnt even show me anything, app is just black on the device

Definatly seems to be related to the back button

**Comment by slavchev** [comment]
Sorry guys, I made a typo yesterday. I meant `this.app`. See https://github.com/NativeScript/android-runtime/commit/a0e4161e0622da1430ac858e2cb96336d96e09f6

**Comment by gabrielbiga** [comment]
Unfortunately this bug is crashing my application as well and I don't have any idea what to do.

**Comment by slavchev** [comment]
Hi @gabrielbiga 

I already merged this fix in the `master` branch which is published as `@next` npm package. You can test if it works for you using the following commands

```
tns platform remove android
tns platform add android@next
```

**Comment by gabrielbiga** [comment]
Awesome @slavchev! Now it's working. Many thanks!

**Comment by rajarameshvarma** [comment]
I still have this issue. My application fails to run after upgrading to 1.7. I am using android@next for the platform as mentioned in previous post. This is on Windows.

`The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: com.tns.NativeScriptException: NativeScript application not initialized correctly. Cannot create extended JS wrapper.
	at com.tns.Platform.createJSInstanceNative(Native Method)
	at com.tns.Platform.createJSInstance(Platform.java:368)
	at com.tns.Platform.initInstance(Platform.java:343)
	at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:112)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
	... 9 more`

**Comment by slavchev** [comment]
@rajarameshvarma 

I created a new issue https://github.com/NativeScript/android-runtime/issues/400

**Comment by hshristov** [comment]
@rajarameshvarma Could you please try your app with tns-core-modules 1.7.1 and runtime 1.7.1.
If it still crash please open new issue and attach a project which reproduce the issue. We will happily investigate it.
