### ISSUE TITLE
Converters are embedded in list of objects when bound to ListView

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1910]
* Description : 

When you bind a list of objects to a ListView, if you use a converter in `itemTemplate`, it is added of the object itself.

* Project to reproduce : 
[convertersIssueProject.zip](https://github.com/NativeScript/NativeScript/files/209777/convertersIssueProject.zip)

_Launch the project, tap on any item and watch the console, you'll see the converter in the tapped object._

* Technical informations : 
  - tns-core-modules 1.7.1
  - tns-android 1.7.1
  - Windows 10

Bug reproduced by @NathanaelA 

Thanks :+1:

**Comment by guillaume-roy** [comment]
It's the same problem if you use something like that in your `itemTemplate` : 

`<Label text="{{ $value | mySuperConverter }}" class="list-item-secondary" row="2" col="1" />`

`$value` will be added to the object.

**Comment by guillaume-roy** [comment]
Any information is missing ?

**Comment by nsndeck** [comment]
The issue was fixed with commit #1999. Unfortunately it is too late for this commit to enter into the official release. However we already provide `@next` support so if this is a show-stopper our latest version could be used instead of official 2.0 release.

**Comment by guillaume-roy** [comment]
I've just updated to version 2.0.0 and the problem is still there.
