### ISSUE TITLE
Custom title on Android fails with exception

### ISSUE THREAD

**Issue by jahidshohel** [NativeScript/NativeScript#2372]
### Tell us about the problem
Creating a custom title on action gives error on Android. For example -

```
<ActionBar title="Custom Title">
    <StackLayout orientation="horizontal"
                 ios:horizontalAlignment="center"
                 android:horizontalAlignment="left">
        <Image src="res://nativescript_logo" class="action-image"></Image>
        <Label text="ativeScript"  class="action-label"></Label>
    </StackLayout>
</ActionBar>

```

Fails with an error on emulator (note: this is on emulator) for Android, but works on iOS -

![screen shot 2016-06-25 at 09 03 30](https://cloud.githubusercontent.com/assets/15341855/16355373/05e53030-3ab5-11e6-8881-3cd7f367c86c.png)

NOTE: The app does not crash, the error doesn't show up on console. Its just in app stack trace showing as shown in the attached screen shoot.
### Which platform(s) does your issue occur on?
Only on Android (both device and emulator)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.0
- Runtime(s): `tns-android: 2.0.0` and `tns-ios: 2.0.1`.
- Plugin(s): `
"@angular/common": "2.0.0-rc.1",
		"@angular/compiler": "2.0.0-rc.1",
		"@angular/core": "2.0.0-rc.1",
		"@angular/http": "2.0.0-rc.1",
		"@angular/router-deprecated": "2.0.0-rc.1",
		"@angular/platform-browser": "2.0.0-rc.1",
		"@angular/platform-browser-dynamic": "2.0.0-rc.1",
		"@angular/platform-server": "2.0.0-rc.1",
		"nativescript-angular": "0.1.1",
		"tns-core-modules": "2.0.0"`

### Please tell us how to recreate the issue in as much detail as possible.

Create a sample page with above mentioned action bar on `NativeScript`+`TypeScript`+`NG2`. And start emulator `tns livesync android --emulator --watch`.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Already shared above.

**Comment by NickIliev** [comment]
Hello @jahidshohel, 

I have tested the described scenario but was **not** able to reproduce it.
Here are the steps I have followed:
- create new NativeScript+Angular app with `tns create myApp --ng`
- paste the action bar code in **app.component.ts** template
- run the app with `tns livesync android --emulator --watch`

At this point, the app is build successfully on Genymotion emulator Nexus 5 - 6.0.0 (API 23)

Perhaps another part of your app code is causing this behaviour - please share more information in order
to able to reproduce this error (even better an extended sample code that is throwing the error)

**Comment by jahidshohel** [comment]
Hi @NickIliev: Initially I thought so, that may be another part of my code generating problem. To verify that I created a fresh app, and just pasted above code, and same problem. Also to be very sure, I commented out above code and added a <Label> and then it works.

I will share my code later today.

**Comment by NickIliev** [comment]
@jahidshohel were you able to resolve your problem!? 
If not let me know where I can find your sample code to reproduce it.

**Comment by hshristov** [comment]
@jahidshohel This should be fixed in 2.1.0

**Comment by jahidshohel** [comment]
@hshristov I just upgraded to 2.1.0, and the problem still exists. So I think you should reopen this issue.

**Comment by hshristov** [comment]
@jahidshohel Please make sure you have upgraded tns-core-modules to 2.1.0

**Comment by jahidshohel** [comment]
After upgrading I get this error. 

Not sure if my way of upgrading `tns-core-modules` was correct, what I did is, changed `"tns-core-modules": "2.1.0"` on package.json and restarted the app.


![screen shot 2016-07-01 at 23 13 38](https://cloud.githubusercontent.com/assets/15341855/16534638/8f0ec93a-3fe1-11e6-92d7-9ca42004959a.png)

**Comment by jahidshohel** [comment]
Here is my `package.json`
[package.txt](https://github.com/NativeScript/NativeScript/files/344208/package.txt)

**Comment by hshristov** [comment]
The safer path is to delete node_modules, platforms, lib folders then `tns run android`.
We have newer android runtime template and newer tns-core-module-widgets that must all update in order to work correctly.
