### ISSUE TITLE
ReferenceError: console is not defined

### ISSUE THREAD

**Issue by Sulman633** [NativeScript/NativeScript#2953]
Getting this error when I try to run my app on android:

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:

Error calling module function

Error calling module function

Error calling module function

ReferenceError: console is not defined
File: "/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/polyfills/console.js, line: 1, column: 65

StackTrace: 
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/polyfills/console.js', line: 1, column: 66
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/platform.js', line: 5, column: 1
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/main.js', line: 3, column: 18
Frame: function:'require', file:'', line: 1, column: 266

ReferenceError: console is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/polyfills/console.js', line: 1, column: 66
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/tns_modules/nativescript-angular/platform.js', line: 5, column: 1
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/main.js', line: 3, column: 18
Frame: function:'require', file:'', line: 1, column: 266

ReferenceError: console is not defined
File: "<unknown>, line: 1, column: 265

package.json:
![packagejson](https://cloud.githubusercontent.com/assets/11000928/19671956/9df62c54-9a40-11e6-832f-3c9863b19ac0.PNG)

**Comment by tsonevn** [comment]
Hi @Sulman633 
Most probably that problem has been related to issue [#505](https://github.com/NativeScript/nativescript-angular/issues/505). The problem occurred after new angular release, however the issue has been already fixed with new nativescript-angular `1.1.1`. You could follow the above mentioned issue, where has been described, how to solve it or you could review our [template-hello-world-ng](https://github.com/NativeScript/template-hello-world-ng/blob/master/package.json) and to change the your dependencies versions as it is described in the template `package.json` file.

Let me know this help or if I assign you further.

**Comment by Sulman633** [comment]
I tried copying the dependencies from the template and deleted the app of my phone re ran using tns run android and used livesync but the same error is still persistent. Would I have to delete platforms as well?

**Comment by tsonevn** [comment]
Hi @Sulman633,
Before rebuilding the app, remove `platform`,  `node_modules` , `hooks` folders and remove the app from the device or emulator, where you are deploying the app. You could also delete the cache , while running the following command in the `CMD` or 'Terminal' -> `npm cache clear`. Then run `tns run <platform_name>`.
Hope this helps

**Comment by Sulman633** [comment]
@tsonevn  I am still getting the same error after following your instructions. Here is a picture of my current package.json after it was updated.

![packagejson](https://cloud.githubusercontent.com/assets/11000928/19875542/e41e3376-9fa3-11e6-89d4-70280bd22a1d.PNG)

**Comment by tsonevn** [comment]
Hi @Sulman633,
Could you upgrade all dependencies as following the below attached one , remove `platforms`, `node_modules` , `hooks` folders and clean the cache using `npm cache clear` and build again the project with `tns run <platform_name>`.

**package.json**

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.ngtest",
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.1.2",
    "nativescript-angular": "1.1.2",
    "nativescript-theme-core": "^0.1.3",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.3.0"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.6",
    "zone.js": "~0.6.21"
  }
}
```
Hope this will help.

**Comment by Sulman633** [comment]
@tsonevn **We seem to be getting somewhere now the error is different!**

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:

Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/platform", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/main.js', line: 3, column: 18
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/platform", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/main.js', line: 3, column: 18
Frame: function:'require', file:'', line: 1, column: 266

at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException:

Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/platform", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/main.js', line: 3, column: 18
Frame: function:'require', file:'', line: 1, column: 266

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/platform", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:244)
    com.tns.Runtime.run(Runtime.java:238)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/org.nativescript.nightlivefront/files/app/main.js', line: 3, column: 18
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:244)
at com.tns.Runtime.run(Runtime.java:238)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)

![packagejson](https://cloud.githubusercontent.com/assets/11000928/19953301/b395392a-a142-11e6-80ac-d2bbbeabadc4.PNG)

**Comment by tsonevn** [comment]
Hi @Sulman633,

Everything with the dependancies looks fine. Could you confirm that you have deleted `platforms`, `node_modules` and `hooks` folders before rebuilding the app. Regarding to that, it would help if you could share some code with us, which will allow  us the debug your code locally.

Regards,
@tsonevn

**Comment by Sulman633** [comment]
@tsonevn thank you for your help, I seem to have solved the problem by just deleting the whole project and then using your tns-template-hello-world-ng template as the project starting point. I just have one more question, if I don't want the dependencies to update I would just remove the  ^ right? Seems this is been happening to a lot since there are minor patches that break my project time after time. Would you recommend this to stop the updates by removing ^?

**Comment by tsonevn** [comment]
Hi @Sulman633,

You are right in case you do not want your dependencies to be updated you should remove `^`. Without this symbol the app will use the exact dependencies versions, which have been entered in your `package.json` file. Regarding to your second question to be sure that your project will not be breake with change some version change, you could remove `^` from your `package.json` file.

Hope this helps.
