### ISSUE TITLE
iOS emulator closes app after navigation

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#308]
_From @adampresley on June 10, 2015 15:45_

I have started a small project which is exhibiting odd behavior. There are two views, each with ListViews on them, and the second view has a back button. I am running the application in the iOS emulator and experience what appears to be a crash.

* Open the application in iOS emulator
* Tap on *Manage Inventory*. New view will open
* Tap on *Back* button. This will take you back to the first view
* Tap on *Manage Inventory* again. The view opens, then the application closes entirely

Below are the versions of stuff, and the code. If anything else is needed please let me know. Thanks!

**Versions and Specs**

* NativeScript CLI version 1.0.2
* iOS Simulator 8.3
* XCode 6.3.2
* OSX 10.10.3 Yosemite

**app.js**
```js
var application = require("application");

application.mainModule = "dashboard";
application.cssFile = "./app.css";
application.start();
```

**dashboard.xml**
```xml
<Page
		xmlns="http://www.nativescript.org/tns.xsd"
		loaded="onPageLoaded"
		navigatedTo="pageNavigatedTo">
	<GridLayout rows="auto, *">
		<!-- Header -->
		<Border id="header" row="0">
			<Label text="Grocery List" />
		</Border>

		<!-- Menu Items -->
		<ListView items="{{ menuItems }}" row="1" itemTap="onMenuItemTap">
			<ListView.itemTemplate>
				<Label text="{{ text }}" />
			</ListView.itemTemplate>
		</ListView>
	</GridLayout>
</Page>
```

**dashboard.js**
```js
var observableModule = require("data/observable");
var frameModule = require("ui/frame");
var platformModule = require("platform")

var pageData = new observableModule.Observable();

exports.onPageLoaded = function(args) {
	var page = args.object;

	if (platformModule.device.os === "iOS") {
		frameModule.topmost().ios.navBarVisibility = "never";
	}

	if (platformModule.device.os === "Android") {
		frameModule.topmost().android.actionBar.hide();
	}
};

exports.pageNavigatedTo = function(args) {
	var page = args.object;

	pageData.set("menuItems", [
		{ text: "My Lists" },
		{ text: "New List" },
		{ text: "Manage Inventory" },
		{ text: "Manage Stores" }
	]);

	page.bindingContext = pageData;
};

exports.onMenuItemTap = function(args) {
	frameModule.topmost().navigate("manageStores");
};
```

**manageStores.xml**
```xml
<Page
		xmlns="http://www.nativescript.org/tns.xsd"
		navigatedTo="pageNavigatedTo">
	<GridLayout rows="auto, *">
		<!-- Header -->
		<Border id="header" row="0">
			<Label text="Grocery List" />
			<Button text="Add" tap="addStore" />
			<Button text="Back" tap="goBack" />
		</Border>

		<!-- Menu Items -->
		<ListView items="{{ stores }}" row="1">
			<ListView.itemTemplate>
				<Label text="{{ name }}" />
			</ListView.itemTemplate>
		</ListView>
	</GridLayout>
</Page>
```

**manageStores.js**
```js
var observableModule = require("data/observable");
var frameModule = require("ui/frame");
var dialogs = require("ui/dialogs");

var topmost = frameModule.topmost();
var pageData = new observableModule.Observable();

exports.pageNavigatedTo = function(args) {
	var page = args.object;
	
	pageData.set("stores", [
		{ name: "Target" },
		{ name: "Kroger" }
	]);

	page.bindingContext = pageData;
};

exports.addStore = function() {
	dialogs.alert("Adding a store!");
};

exports.goBack = function() {
	var topmost = frameModule.topmost();

	if (topmost.canGoBack) {
		topmost.goBack();
	} else {
		topmost.navigate("dashboard");
	}
}
```

_Copied from original issue: NativeScript/nativescript-cli#549_

**Comment by vchimev** [comment]
@adampresley this issue seems to be already fixed in version 1.1.0

**Comment by adampresley** [comment]
I'm afraid the issue is not resolved. I am including a link with a video demonstration of the issue in action. Please re-open this ticket. https://dl.dropboxusercontent.com/u/5726689/demonstration-of-nativescripti-ios-issue.mov

**Comment by ligaz** [comment]
Hey @adampresley,

Have you updated the the app itself and the tns_modules used in the application? [Here](https://github.com/NativeScript/NativeScript/issues/316#issuecomment-112309530) is a procedure how you can do this.

**Comment by adampresley** [comment]
Hi @ligaz . I went through the procedure listed in the link above and it worked! Thanks a bunch.I appreciate everyone's help.
