### ISSUE TITLE
Pseudo selector ':' not applying when Button has backgroundColor

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/NativeScript#3237]
### Did you verify this is a real problem by searching [Stack Overflow]
yes

### Tell us about the problem
Pseudo selector : not applying when button has backgroundColor

### Which platform(s) does your issue occur on?
Android.
I didn't test ios

### Please tell us how to recreate the issue in as much detail as possible.
`<button [text]="'hello world'" backgroundColor="green" ></button> `
 `Button:highlighted {
    background-color: red;
}`

**Comment by bradmartin** [comment]
Android 21+?

**Comment by kazemihabib** [comment]
no , Android 19.

**Comment by tsonevn** [comment]
Hi @kazemihabib, 
Thank you for reporting this issue. 
This behavior has been logged in issue [#3172](https://github.com/NativeScript/NativeScript/issues/3172). Regarding to that, the problem has been fixed with PR [#3219](https://github.com/NativeScript/NativeScript/pull/3219) and will be available with NativeScript 2.5. In the mean time you could use `@next` modules. `tns plugin remove tns-core-modules`,  `tns plugin add tns-core-modules@next`

Regards,
@tsonevn

**Comment by kazemihabib** [comment]
Hi, @tsonevn ,
I don't think that issue is related to this issue.
and I tried @next version and the problem still exist.

**Comment by tsonevn** [comment]
Hi @kazemihabib, 

I tested the given scenario with `@next` modules and everything with the pseudo selectors seems to work as expected.  Could you try the below-attached steps to verify, whether you will have the same problem.

1. `tns create <project name> --ng`
2. `tns plugin remove tns-core-modules`
3. `tns plugin add tns-core-modules@next`
4. add the following code in `main-page.xml`
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
        <Label text="Tap the button" class="h1 text-center"/>
        <Button text="TAP" tap="{{ onTap }}" />
        <Label text="{{ message }}" class="h2 text-center" textWrap="true"/>
    </StackLayout>
</Page>

```
5. add the following code in `app.css`
```
Button{
    background-color:green;
}
Button:highlighted { background-color: red; }
```

Let me know. whether this helps.

**Comment by kazemihabib** [comment]
@tsonevn : I tested your code and it works.
but if you set the background color in xml directly it will not work. like this:
`<button [text]="'hello world'" backgroundColor="green" ></button>`

**Comment by tsonevn** [comment]
Hi @kazemihabib,
Thank you for writing us back.

Setting style properties in the XML is with higher priority and the pseudo selectors set in the CSS will be ignored. However, if you still need to set `backgroundColor` in XML directly. Could you specify your case and we will provide possible solution.

Hope this helps.

**Comment by kazemihabib** [comment]
Hi, @tsonevn ,
thanks for your response.

At first I thought it doesn't work at all,but after you send me solution I found that it works but just with css(because the reason you mentioned above). That solves my problem.
