### ISSUE TITLE
Images randomly get swapped on Android

### ISSUE THREAD

**Issue by alexziskind1** [NativeScript/NativeScript#3747]
## Please, provide the details below:
On Android (not iOS) images that are either deployed as resources or in a separate folder sometimes get swapped for other images at random. The repository with all the code is listed below and a video was created to demonstrate the problem.

### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
I could not find an existing issue.

### Which platform(s) does your issue occur on?
iOS/Android/Both
The problem is on Android. It is working fine on iOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.2
- Cross-platform modules: 2.5.1
- Runtime(s): 2.5.0 for iOS and Android
- Plugin(s): 
    "nativescript-angular": "1.4.1",
    "nativescript-telerik-ui": "1.6.1",
    "nativescript-theme-core": "1.0.3",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.2.0",
    "tns-core-modules": "2.5.1"

### Please tell us how to recreate the issue in as much detail as possible.
I created a video of the problem and it can be seen on youtube here: https://youtu.be/WUszWXxHjWI
Clone the repo and run the project. I use Genymotion as my emulator on Mac Sierra and I've tried this on two different Macs.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Yes, the complete project is in the following repo: https://github.com/alexziskind1/looptidoo

Thanks,
Alex

**Comment by NickIliev** [comment]
Hey, @alexziskind1 we've tested your application on several AVD emulators and on several real devices (API25, API23 and API19) and it seems that this issue is only reproducible under one LG G3 API19 and in the same time everything is working as expected on the other AVD emulators and devices. I had a similar issue caused by the Geny emulators (the reason I stopped using Genymotion). 

Can you try testing your application against a real device or [an AVD emulator.](http://docs.nativescript.org/tooling/android-virtual-devices)

Meanwhile, I will investigate what's the reason for this one to be reproducible only on a single LG device and will come back to you when additional info is available

**Comment by davek1979** [comment]
I'd like to report I have encountered the same problem on a generic 10.1 WXGA Tablet AVD emulator.
I have 2 different images in my view and somehow, the view contained the same image twice despite having been recompiled and resynced on emulator start. XML contained the correct markup of course. Only a subsequent resync corrected the issue.

**Comment by alexziskind1** [comment]
Just tried with a standard (non-Genymotion) Android emulator and the problem doesn't exist there.
For those interested, I'm now using an AVD with the following config:
Nexus 5
Android 7.1.1 API Level 25
Google APIs Intel Atom (x86) (with HAXM)
RAM 2048 VM Heap 64
Storage 500MiB

--

**Comment by NathanaelA** [comment]
@alexziskind1 - Just because the AVD works doesn't mean the issue is solved.   I'm pretty sure this is a timing issue with the reuse of the image component/memory.  So because AVD runs slightly slower you don't see the issue; but because Geny (& some real devices!) runs faster than AVD, you will see it.

**Comment by alexziskind1** [comment]
Yes the issue is not solved as it is still happening on Geny and even other
android AVD. But for those folks that need to have a temporary working
alternative, I've provided some settings.

This is still a problem though.

On Mar 13, 2017, at 5:50 PM, Nathanael Anderson <notifications@github.com>
wrote:

@alexziskind1 <https://github.com/alexziskind1> - Just because the AVD
works doesn't mean the issue is solved. I'm pretty sure this is a timing
issue with the reuse of the image component/memory. So because AVD runs
slightly slower you don't see the issue; but because Geny (& some real
devices!) runs faster than AVD, you will see it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NativeScript/NativeScript/issues/3747#issuecomment-286254947>,
or mute the thread

**Comment by alexziskind1** [comment]
@NickIliev I've moved the effected code into the master branch in the referenced repo. I omitted the branch in my original post.

**Comment by NickIliev** [comment]
related to [https://github.com/NativeScript/NativeScript/issues/2861](https://github.com/NativeScript/NativeScript/issues/2861)

Note - The issue is not related to file naming and occurs randomly only on some specific devices and mainly when using Genymotion.

**Comment by TLmaK0** [comment]
Same problem here, this happens after last release I did without change app code. It was working until last month. I think it's a problem with a library update.

**Comment by SvetoslavTsenov** [comment]
Also reproducible with Groceries on api level 19

**Comment by codeback** [comment]
I am experiencing the same problem. I've installed the last version of tns-core-modules (tns-core-modules@3.1.0-2017-05-17-6629) and the problem persists.

Is there any way to test the proposed solution?

Thanks!

**Comment by hshristov** [comment]
@codeback You need the latest version of tns-core-modules-widgets@next
