### ISSUE TITLE
Implementation of the AppDelegate fail

### ISSUE THREAD

**Issue by Johnny1102** [NativeScript/NativeScript#4518]
### Tell us about the problem
Hi all,
I need to use nativescript-background-fetch module. First step of implementing this module is the Implementation of the AppDelegate:
```
if (app.ios) {
  class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];
      // BackgroundFetch delegate method
      public applicationPerformFetchWithCompletionHandler(application: any, completionHandler:any) {
        BackgroundFetch.performFetchWithCompletionHandler(completionHandler);
      }
    }
   app.ios.delegate = MyDelegate;
}
```
But the row "app.ios.delegate = MyDelegate" throws this error: "file:///app/tns_modules/tns-core-modules/application/application.js:211:87: JS ERROR Error: Value is not a class."

Do you know what could cause this error?

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.1
- Cross-platform modules: 3.1.0
- Runtime(s): tns-ios: 3.1.0

**Comment by NickIliev** [comment]
Hey @Johnny1102  I have implemented nativescript-background-fetch plugin using the exact same workflow as you have described (and as described in the plugin's README) but was not able to reproduce the error.

[Here you can find the test application ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4518)I have created - you can try it at your side and let me know if you still experience the same error.

**Comment by tsonevn** [comment]
Hi @Johnny1102, 
Do you still facing the same problem or you were able to resolve the issue on your side?

**Comment by Johnny1102** [comment]
Hi,
I'm sorry for a late answer. The problem still occurs. But I don't need this solution anymore. I found some another solution for what I need.
I cannot continue with fixing this problem now.

Thank you for your answer
