### ISSUE TITLE
Textfield - changing the secure value changing font css

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#4626]
### Did you verify this is a real problem by searching [Stack Overflow]
Yes, I found this 

### Tell us about the problem
I created a "password" textfield and a button of "show-hide" that responsible for changing the "secure" value of the mentioned textfield.
The problem in when I press the "show-hide" button the font css properties change.

This is a video on the problem in my end -> [https://www.screencast.com/t/ShDaR8cK](url)

### Which platform(s) does your issue occur on?
Android.
Didn't check on IOS.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.2
- Cross-platform modules: 3.1.0
- Runtime(s): 3.1.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

html file.
```
<StackLayout>
    <StackLayout orientation="horizontal">
        <Label text="Password" class="field-label"></Label>
        <Label [text]="passwordSecureModeText" class="show-hide-text" (tap)="secureModeChange()"></Label>
    </StackLayout>
    <TextField class="field-text-area" [hint]="Password" [secure]="passwordSecureMode" [(ngModel)]="password"></TextField>
</StackLayout>
```

ts file
```
export class SignUpComponent {
    public password: string;
    public passwordSecureMode: boolean = true;
    public passwordSecureModeText: string = "Show";

    private secureModeChange() {
        this.passwordSecureMode = !this.passwordSecureMode;
        this.passwordSecureModeText = this.passwordSecureMode ? "Show" : "Hide";
    }
}
```

css file
```
.field-label {
    color: #f2f2f2;
    font-family: 'Product Sans',Arial,sans-serif;
    font-size: 22px;
    font-weight: 300;
}

.show-hide-text {
    color: #f2f2f2;
    font-family: 'Product Sans',Arial,sans-serif;
    font-size: 14px;
    font-weight: 100;
    vertical-align: center;
    margin-left: 50px;
    margin-right: 50px;
}

.field-text-area {
    color: #f2f2f2;
    border-bottom-color: #f2f2f2;
    font-family: 'Product Sans',Arial,sans-serif;
    font-size: 18px;
    font-weight: 100;
    placeholder-color:#f2f2f2;
}
```

Hope that is enough information. :)

Thank you!

**Comment by tsonevn** [comment]
Hi @shabib3,
Thank you for reporting this behavior,
I tested this case on my side and have to confirm that this is a real issue for Android.
For your convenience, I am attaching sample project, where this problem could be reproduced.
For further info and possible workaround, keep track on the issue 
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1192738/Archive.zip)

**Comment by shabib3** [comment]
@tsonevn  Thanks!
I will follow this issue :)

**Comment by CristianHCol** [comment]
The issue still persist??
I reproduce this issue today.
Thanks

**Comment by volodyakurpita** [comment]
And there is still a problem now. Also I can reproduce this today.

**Comment by surdu** [comment]
In [this Playground example](https://play.nativescript.org/?template=play-js&id=HR92UG&v=4) I noticed that when I set the `font-size` for the TextView wrapper element (comented out in `app.css`) the font difference is fixed, but this fix doesn't seem to always work.

**Comment by sulymkaa** [comment]
is there any updates for this issue?

**Comment by tsonevn** [comment]
Hi @sulymkaa,
The issue is still under review. Meanwhile, you can check if the suggestion provided by @surdu will work for you.

**Comment by A-Shleifman** [comment]
![2019-06-13 18 10 00](https://user-images.githubusercontent.com/1146193/59452838-842cfe80-8e06-11e9-9f02-84456645dca2.gif)

**Comment by mpht** [comment]
Here is a workaround for this (tested on android only - but should be compatible with android)

![pw](https://user-images.githubusercontent.com/50829690/60595052-88658f80-9da6-11e9-8a34-b72b7c3ae162.gif)

This helped me for finding the workaround: https://github.com/chrisjenx/Calligraphy/issues/186

Wait until TextField is loaded (tfLoaded)
`<TextField (loaded)="tfLoaded($event) autocorrect="false" [ios:secure]="!showPassword" hint="password" [(ngModel)]="text"></TextField>`

The loaded function:
`public tfLoaded(args) {
if (isAndroid) {
this.androidTf = args.object.android;
this.typeface = args.object.android.getTypeface();
this.updateVisibility();
}
}`

updateVisibility() looks like this:
`private updateVisibility() {
    // secure or plain text
    this.androidTf.setInputType(this.showPassword ? 16385 : 129)
    // make sure to use the initial typeface
    this.androidTf.setTypeface(this.typeface);
    // move cursor back to the end
    this.androidTf.setSelection(this.androidTf.length());
  }`

and somewhere there is the toggle button (in my case the eye symbol:

`  public toggleVisibility(): void {
    // for iOS let nativescript do the work <TextField [ios:secure]="!showPassword" .... >
    this.showPassword = !this.showPassword;
    // for android we do it like this
    if (isAndroid && this.typeface) {
      this.updateVisibility();
    }
  }`

**Comment by Firetrip** [comment]
When is this issue going to be fixed? Is it even planned to be fixed? Seems like a basic behaviour a product with version 6+ should not have.

**Comment by Arystosedes** [comment]
In 2020 we still waiting for fixing..  :/

**Comment by NickIliev** [comment]
@Firetrip @Arystosedes the product is open-source and we are accepting PR. If you are interested in contributing then please follow the contributing guidelines ([here ](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md)and [here](https://www.nativescript.org/contribute))
