### ISSUE TITLE
Question: Core Module change causing style to break

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#4728]
## Please, provide the details below:

I normally wouldn't open an issue for this type of bug without investigating but too many people have hit the same issue and I don't recall any changes in the plugins in quite some time and I haven't had time to debug the issue. The issue is on both cardview and floatingactionbutton plugin repos have been opened with the same issue recently. 

https://github.com/bradmartin/nativescript-cardview/issues/64
https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57

### Which platform(s) does your issue occur on?

Android for sure

### Please provide the following version numbers that your issue occurs with:
See issue

### Please tell us how to recreate the issue in as much detail as possible.

Run latest core modules with either the cardview or fab plugin as described in the issue on the repos. Someone has reported a revert in the core-modules fixed the issue and then when updating to the latest it breaks again.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Demo code on repos should be sufficient.

**Comment by tsonevn** [comment]
Hi @bradmartin,
Thank you for reporting this issue.
We reviewed the described scenario and indeed there is an issue with getting drawable from the native view, which in some cases is a null object. 
We will investigate further how to resolve this problem and will provide a fix inside the `tns-core-modules`.
Regards,
@tsonevn

**Comment by hshristov** [comment]
Hi @bradmartin 

Thanks for reporting this. It is fixed in the master branch with this PR: https://github.com/NativeScript/NativeScript/pull/4742 and will be live in 3.2

**Comment by SP1966** [comment]
After updating this issue is still unresolved in both of the following plugins:

https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57
https://github.com/bradmartin/nativescript-cardview/issues/64

**Comment by jafsparrow** [comment]
Hi All,

Any update on this? anybody figured out the reason and way to fix it.?

**Comment by bradmartin** [comment]
@hshristov - I believe an issue might still be present on Android 6 per this comment https://github.com/bradmartin/nativescript-floatingactionbutton/issues/57#issuecomment-331425213

**Comment by jafsparrow** [comment]
Thanks Brad, I will try this on 7 then..! 
But there's gotta be a reason for this..!  I'm facing same kind of issue with FAB and CardView.

**Comment by hshristov** [comment]
@bradmartin @jafsparrow @SP1966 
Addition to the original fix because of bug in Android 6.0 API 23
https://github.com/NativeScript/NativeScript/pull/4959

**Comment by jafsparrow** [comment]
Thank you @hshristov.

for FAB and CardView
I think explicitly giving the color property is solving the issue (can be used a hack fix). 

I was also testing the dropdown plugin which is also breaking if some properties are not given in css (specifying the properties in css fixes the issue). 

thanks guys for your helps..
