### ISSUE TITLE
Android textfield blur is fired multiple times when inside listview item

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#5820]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
On Android when listview item has a textfield and it looses focus blur event is fired multiple times.  

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.1
- Cross-platform modules: 3.4.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
Please clone and run [this](https://github.com/terreb/tnslistviewtextfield) sample project on Android. Tap one textfield then another and watch console logs.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
Please see above.

**Comment by NickIliev** [comment]
@terreb the issue is resolved with tns-core-modules@4.0.0 - test Playground demo can be found [here](https://play.nativescript.org/)

**Comment by terreb** [comment]
@NickIliev, I updated cli to 4.0.1, tns-core-modules to 4.0.0, tns-android to 4.0.1, but the issue still persists.  The link you mentioned in your comment doesn't show an example with listview and textfield.

**Comment by aligg73** [comment]
Why is this issue closed when the issue has not been resolved?

**Comment by NickIliev** [comment]
I was able to reproduce the issue with [the Playground ](https://play.nativescript.org/?template=play-tsc&id=7fXlJm)provided by @terreb (small modification added).

**Bug:** It seems that the `blur` event for text fields inside ListView item template will **initially** be fired from all fields in the visible cells.  After the initial blur, the behavior is as expected and the blur is only triggered once for each single text field.

**Comment by terreb** [comment]
@NickIliev, thank you, but other than the issue you mentioned I have the blur event fired multiple times while tapping textfields. Initially it's indeed fired more times (7-10?), but even after that when I tap textfields I see the blur is being fired 2-3 times.
