### ISSUE TITLE
IOS: Actionbar Flat property not aligning the content of the page correctly after setting it to true

### ISSUE THREAD

**Issue by btaluy** [NativeScript/NativeScript#6063]
### Tell us about the problem
When setting the Actionbar property flat to true, this gives weird aligning of the content, the content falls back behind the actionbar and the content needs margin top to move the content down.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.0
- Runtime(s): TNS-ios: 4.1.1
- Plugin(s): N/A

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
<ActionBar [title]="" class="" flat="true">
  <NavigationButton android:icon="res://ic_back" (tap)="onBack()"></NavigationButton>
</ActionBar>

<StackLayout/GridLayout/DockLayout..etc etc>
 // Content
</StackLayout/GridLayout/DockLayout..etc etc>
```

![screen shot 2018-07-13 at 11 05 22](https://user-images.githubusercontent.com/22479262/42684934-dfd3dfba-8691-11e8-8c8c-295f49e8858c.png)
This how it looks at the moment when giving margin-top of 16 to the content container 

**NEW UPDATE!!**
Bug can be reproduced with the following project:

https://github.com/YvesCandel/nativescript-flat-actionbar-bug/commits/master

It seems to be a problem when defining a transition to the routerextension.navigate function.
If we remove the transition we add then it works as expected.

**Comment by tsonevn** [comment]
Hi @btaluy,
 I tested your case on my side, however, was unable to recreate the issue. I am attaching a [link](https://play.nativescript.org/?template=play-tsc&id=dF1XwY) to the NativeScript Playground project. Please review it and make the needed changes, which will help us to recreate the problem.

**Comment by btaluy** [comment]
I forgot to mention that I am using nativescript-angular @tsonevn

**Comment by tsonevn** [comment]
HI @btaluy,
I tested the issue in a sample NativeScript Angular project, however, I am still unable to recreate the problem. Please review the attached project and make the needed changes, which will allow us to reproduce the problem.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/2196718/Archive.zip)

**Comment by tsonevn** [comment]
closing due to inactivity

**Comment by btaluy** [comment]
Bug can be reproduced with the following project:

https://github.com/YvesCandel/nativescript-flat-actionbar-bug/commits/master

It seems to be a problem when defining a transition to the routerextension.navigate function.
If we remove the transition we add then it works as expected.

**Comment by yonkoGH** [comment]
Same problem for me ??

**Comment by btaluy** [comment]
@tsonevn Any news on this issue?

**Comment by tsonevn** [comment]
Hi @btaluy,
This issue should be fixed with NativeScript 5.0

**Comment by JakubPawlak** [comment]
Unfortunately, it hasn't been fixed. This is the simple Playground to show the case: https://play.nativescript.org/?template=play-ng&id=CBt1Ou
The problem appears when the <page-router-outlet> is wrapped in any layout.

**Comment by b4rtt** [comment]
Same problem here. 

First screenshot is with flat=false and second one is with flat=true...

https://imgur.com/a/OhMtRGT

**Comment by marcelomiranda90** [comment]
+1

**Comment by demetrio812** [comment]
I can confirm I can reproduce the problem (using the latest version)

**Comment by yoat** [comment]
Try again with NativeScript 5.2.  The issue I had (gap below flat ActionBar) has been resolved, so some work has gone into the NS 5.2 flat Action Bar handling.

**Comment by MartoYankov** [comment]
As stated above, this issue is fixed in 5.2 with https://github.com/NativeScript/NativeScript/pull/6862

**Comment by harryt04** [comment]
Can comfirm this is still not fixed. I'm on v5.3.0-rc-2019-03-22-063928-01

**Comment by MartoYankov** [comment]
@harryt04 Can you try it with v5.2.1

**Comment by harryt04** [comment]
@MartoYankov I've tried it with v5.2.1, 5.2.2 and the most recent release candidate. The issue persists. For us, we have a stacklayout wrapping our page-router-outlet. I saw on another issue thread someone saying that they had the same use case and issue, although I can't seem to find that thread now. 

For now, our team has decided to change the action bar flat="false", and change our styling such that we aren't bothered by the non flat action bar. The only time the page doesn't lay out correctly is when the action bar flatness is set to true.

**Comment by MartoYankov** [comment]
@harryt04 Flat bars have been a nightmare. However, this issue has been fixed in 5.2.1 and we have found out that it returned with 5.2.2. Here is the new issue that was opened - https://github.com/NativeScript/NativeScript/issues/7065. If this is not the issue you are experiencing, please open a new one. If you can attach a playground with a simple example that demonstrates your setup, it would be great.
