### ISSUE TITLE
keyboardType integer in TextField is password

### ISSUE THREAD

**Issue by Noppey** [NativeScript/NativeScript#8285]
In Android, when using keyboardType="integer" in a TextField, the input is hidden in dots, as in a password type.

**Comment by NickIliev** [comment]
@Noppey the issue is resolved via[ this PR](https://github.com/NativeScript/NativeScript/pull/8250) and the fix is currently in the next branch (npm i tns-core-modules@next). It will be officially published with the upcoming release.

**Comment by Noppey** [comment]
I updated to the latest next branch, but the problem still shows up.

Op wo 29 jan. 2020 14:16 schreef Nick Iliev <notifications@github.com>:

**Comment by NickIliev** [comment]
@Noppey you are absolutely right - I've posted the PR but only for editable-text-base class... forgot to update the code for TextField as well - fixing the issue as we speak.

Will be resolved[ when this PR is merged.](https://github.com/NativeScript/NativeScript/pull/8290)
