### ISSUE TITLE
CocoaPods could not find compatible version for pod "Socket.IO-Client-Swift" 

### ISSUE THREAD

**Issue by agardes** [NativeScript/NativeScript#9417]
My environnement :

- Nativescript version : 8.0.0
- Nativescript vue : 2.8.1

When launching `tns debug iOS` on simulator, I come across this issue :
```
[!] CocoaPods could not find compatible versions for pod "Socket.IO-Client-Swift":
  In Podfile:
    Socket.IO-Client-Swift (from `https://github.com/triniwiz/socket.io-client-swift.git`)

Specs satisfying the `Socket.IO-Client-Swift (from `https://github.com/triniwiz/socket.io-client-swift.git`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `iOS` with version `9.0` on target `appgv` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
'pod install' command failed.
```

I found a workaround which is adding `platform:"ios","10.0"` at the beginning of my Podfile. But I have to do this everytime. Is there any way to fix this ? I tried to post this issue on https://github.com/triniwiz/socket.io-client-swift but there is no issue tabs since it's a refork. 

Thanks a lot

**Comment by triniwiz** [comment]
Thanks for the reminder , I published a new version with the fix on the plugin

**Comment by agardes** [comment]
Thanks a lot @triniwiz. I did a `tns clean` and a `npm i` with nativescript-socketio:"^3.3.1" version, but the issue still occurs. Am I updating it wrong ? 

Thanks again!

**Comment by triniwiz** [comment]
You should be on `@triniwiz/nativescript-socketio` 5x
